<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>potatus hub</AssemblyName>
    <RootNamespace>PotatusHub</RootNamespace>
    <Version>0.3.0</Version>
    <ApplicationIcon>Resources\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Using Remove="System.Drawing" />
    <Using Remove="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="8.0.1" />
    <Resource Include="Resources\AppIcon.ico" />
  </ItemGroup>
</Project>
